data_path: data/data.yaml
conf_file: configs/yolov6l_finetune.py
img_size: 640
batch_size: 64
epochs: 400
workers: 8
device: 0,1,2,3
eval_interval: 20
eval_final_only: false
heavy_eval_range: 50
check_images: false
check_labels: false
output_dir: ./runs/train
name: exp
dist_url: env://
gpu_count: 0
local_rank: 0
resume: false
write_trainbatch_tb: false
stop_aug_last_n_epoch: 15
save_ckpt_on_last_n_epoch: -1
distill: false
distill_feat: false
quant: false
calib: false
teacher_model_path: null
temperature: 20
rank: 0
world_size: 4
save_dir: runs/train/exp5
